# Generated by Django 4.2.28 on 2026-02-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('employee_id', models.CharField(max_length=30, verbose_name='Employee ID')),
                ('department', models.CharField(choices=[('Police Department', 'Police Department'), ('Fire Department', 'Fire Department'), ('Utilities', 'Utilities'), ("City Manager's Office", "City Manager's Office"), ('Health Department', 'Health Department'), ('Finance', 'Finance'), ('Public Works', 'Public Works'), ('Parks & Recreation', 'Parks & Recreation'), ('City Clerk', 'City Clerk'), ('Planning & Zoning', 'Planning & Zoning')], max_length=80, verbose_name='Department')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('category', models.CharField(choices=[('hardware', 'Hardware — Computers, Printers, Devices'), ('software', 'Software — Applications, Licenses, OS'), ('network', 'Network — Connectivity, WiFi, VPN'), ('email', 'Email & Communication'), ('security', 'Security — Passwords, Access, Accounts'), ('phone', 'Phone / VOIP Systems'), ('server', 'Servers & Infrastructure'), ('data', 'Data & Reporting')], max_length=30, verbose_name='Category')),
                ('subtype', models.CharField(blank=True, choices=[('', '— Optional —'), ('complete_outage', 'Complete Outage / Not Working At All'), ('no_boot', "Not turning on / won't boot"), ('slow', 'Slow performance / intermittent'), ('display', 'Display / monitor issue'), ('peripheral', 'Peripheral not recognized'), ('app_crash', 'Application crash / error code'), ('no_login', 'Cannot log in / locked out'), ('no_internet', 'No internet / network access'), ('slow_conn', 'Slow connection'), ('pw_reset', 'Password reset needed'), ('new_user', 'New user / onboarding setup'), ('data_loss', 'Data loss / corruption concern')], max_length=30, verbose_name='Sub-Type')),
                ('title', models.CharField(max_length=120, verbose_name='Brief Summary')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('asset_tag', models.CharField(blank=True, max_length=40, verbose_name='Asset Tag')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='Location')),
                ('phone_ext', models.CharField(blank=True, max_length=10, verbose_name='Phone Ext')),
                ('user_priority', models.IntegerField(choices=[(4, 'Low — Minor issue, no work stoppage'), (3, 'Medium — Workaround exists, productivity affected'), (2, 'High — Work is halted, team affected'), (1, 'Critical — System down, department or city-wide')], default=4, verbose_name='User-Selected Priority')),
                ('routing_tier', models.CharField(blank=True, max_length=30, verbose_name='Dept Tier')),
                ('routing_tier_label', models.CharField(blank=True, max_length=60, verbose_name='Tier Label')),
                ('routing_team', models.CharField(blank=True, max_length=100, verbose_name='Assigned Team')),
                ('routing_sla', models.CharField(blank=True, max_length=20, verbose_name='SLA Target')),
                ('routing_effective_priority', models.IntegerField(default=4, verbose_name='Effective Priority')),
                ('routing_was_modified', models.BooleanField(default=False, verbose_name='Priority Auto-Adjusted')),
                ('routing_reasons', models.TextField(blank=True, verbose_name='Routing Reasons (JSON)')),
                ('routing_escalation_path', models.TextField(blank=True, verbose_name='Escalation Path (JSON)')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
